[package]
name = "duokan-rooter"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
nix = "0.22.1"

[dependencies.zip]
version = "0.5.13"
default-features = false
features = ["deflate"]
